services:
  web:
    image: ghcr.io/lukazsh/ip-validator:latest
    build: .
    ports:
      - "80:80"
    
    environment:
      DB_HOST: db
      DB_NAME: ip_validator
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - db
    networks:
      - app-net
  db:
    image: mysql:8.0
    container_name: ip-validator-db
    restart: always
    env_file: .env
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-net
  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - app-net

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro 
      - ./monitoramento/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - app-net

  grafana:
    image: grafana/grafana:10.1.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoramento/grafana/loki.yml:/etc/grafana/provisioning/datasources/loki.yml
    env_file: .env
    restart: unless-stopped
    networks:
      - app-net

volumes:
  db_data:

networks:
  app-net:
    driver: bridge
