version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ip-validator_web
    volumes:
      - /var/www/ip-validator:/var/www/html
    ports:
      - "80:80"
