version: '3.8'

services:
  # Serviço da aplicação web (PHP + Apache)
  web:
    build: .
    container_name: ip-validator-web
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=ip_validator_db
      - DB_USER=validator_user
      - DB_PASSWORD=super_secret_password
      - TZ=America/Sao_Paulo
    depends_on:
      - db

  # Serviço para o banco de dados MySQL
  db:
    image: mysql:8.0
    container_name: ip-validator-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=very_strong_root_password
      - MYSQL_DATABASE=ip_validator_db
      - MYSQL_USER=validator_user
      - MYSQL_PASSWORD=super_secret_password
      - TZ=America/Sao_Paulo
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: