groups:
  - name: ip-validator-security-alerts
    rules:
      - alert: SuspiciousLoginActivity
        expr: |
          sum(rate({job="php_app", service="ip-validator"} | json | event="authentication_attempt" | status="failed" [1m])) > 10
        for: 5m
        labels:
          severity: warning
          component: auth
          service: ip-validator
        annotations:
          summary: "High number of failed login attempts detected"
          description: "More than 10 failed login attempts per minute detected in the last 5 minutes. This could indicate a brute force attack."
          
      - alert: PossiblePresenceFraud
        expr: |
          max(count by (client_ip) (count_over_time({job="php_app", service="ip-validator"} | json | event="qr_code_generation" | status="success" [1h]))) > 3
        for: 0s
        labels:
          severity: warning
          component: admin
          service: ip-validator
        annotations:
          summary: "Possible presence fraud detected"
          description: "Same IP address generated more than 3 QR codes in the last hour. This could indicate fraudulent activity."
          
      - alert: BruteForceAttack
        expr: |
          max(count by (client_ip) (count_over_time({job="php_app", service="ip-validator"} | json | event="authentication_attempt" | status="failed" [5m]))) > 5
        for: 2m
        labels:
          severity: critical
          component: auth
          service: ip-validator
        annotations:
          summary: "Brute force attack detected"
          description: "Single IP address has more than 5 failed login attempts in 5 minutes. IP: {{ $labels.client_ip }}"

  - name: ip-validator-infrastructure-alerts
    rules:
      - alert: DatabaseConnectionFailure
        expr: |
          sum(rate({job="php_app", service="ip-validator"} | json | event="db_connection" | status="failed" [5m])) > 0
        for: 2m
        labels:
          severity: critical
          component: database
          service: ip-validator
        annotations:
          summary: "Database connection failures detected"
          description: "Database connection failures detected in the last 5 minutes. This indicates infrastructure issues."
          
      - alert: HighDatabaseQueryDuration
        expr: |
          avg(avg_over_time({job="php_app", service="ip-validator"} | json | event="db_operation" | unwrap duration_ms [5m])) > 2000
        for: 10m
        labels:
          severity: warning
          component: database
          service: ip-validator
        annotations:
          summary: "High database query duration"
          description: "Average database query duration is above 2 seconds for the last 10 minutes. Current average: {{ $value }}ms"
          
      - alert: QRCodeGenerationFailures
        expr: |
          sum(rate({job="php_app", service="ip-validator"} | json | event="qr_code_generation" | status=~"failed|error" [5m])) > 0.1
        for: 5m
        labels:
          severity: warning
          component: admin
          service: ip-validator
        annotations:
          summary: "QR Code generation failures"
          description: "QR Code generation failures detected. This could indicate issues with the admin system or file permissions."

      - alert: ContainerRestarts
        expr: |
          sum(count_over_time({job=~".+"} |~ "restart" [10m])) > 2
        for: 1m
        labels:
          severity: warning
          component: infrastructure
          service: ip-validator
        annotations:
          summary: "Container restarts detected"
          description: "Multiple container restarts detected in the last 10 minutes. This indicates infrastructure instability."

      - alert: HighErrorRate
        expr: |
          (sum(rate({job="php_app", service="ip-validator"} | json | status=~"failed|error" [5m])) / sum(rate({job="php_app", service="ip-validator"} | json [5m]))) * 100 > 5
        for: 5m
        labels:
          severity: warning
          component: application
          service: ip-validator
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for the last 5 minutes. Current rate: {{ $value }}%"

  - name: ip-validator-performance-alerts
    rules:
      - alert: LowLogVolume
        expr: |
          sum(rate({job="php_app", service="ip-validator"}[5m])) < 0.01
        for: 10m
        labels:
          severity: warning
          component: monitoring
          service: ip-validator
        annotations:
          summary: "Low log volume detected"
          description: "Very low log volume detected. This might indicate that the application is not functioning properly or logs are not being collected."
          
      - alert: HighAuthenticationLatency
        expr: |
          avg(avg_over_time({job="php_app", service="ip-validator"} | json | event="authentication_attempt" | unwrap duration_ms [5m])) > 5000
        for: 5m
        labels:
          severity: warning
          component: auth
          service: ip-validator
        annotations:
          summary: "High authentication latency"
          description: "Authentication operations are taking longer than 5 seconds on average. Current average: {{ $value }}ms"